name: morphomics_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cython
  - cached-property
  - h5py>=2.8.0
  - ipython_genutils
  - ipykernel
  - nbformat>=4.2.0
  - matplotlib>=3.2.0
  - networkx
  - numpy<1.25
  - pandas
  - scikit-bio
  - scikit-learn>=0.19.1
  - scipy>=0.13.3
  - tomli
  - torch=2.6.0 
  - plotly
  - seaborn
  - kaleido
  - pip
  - pip:
      - morphon>=0.0.8
      - pylmeasure>=0.2.0
      - torch-geometric
      - torch-scatter==2.1.2 
      - fa2-modified
      - umap-learn>=0.3.10
      - wandb
