# morphOMICs pipeline and parameter setup

# sequential list of executables
# Choices of executables: Input, Load_data, Clean_frame, Bootstrap, Persistence_Images, UMAP, 
#                         Palantir, Plotting, Mapping, Clear_morphframe, Prepare_ReductionInfo, 
#                         Sholl_curves, Morphometrics
# This is an example of a standard morphOMICs pipeline to obtain the morphological spectrum
Protocols = [
        "Load_data",
        "Clean_frame",
        "Bootstrap",
        "Persistence_Images",
        "Mapping",
        "Prepare_ReductionInfo",
        "Plotting",
    ]

# set this if you have ran morphOMICs with this set of parameters and you want to re-do it but with the latest saved instance
# use case: you tried running run_morphomics.py but it failed at some protocol
load_previous_instance = false
# set this if you want to always save last instance
save_last_instance = true
path_to_last_instance = "/media/drive_siegert/RyCu/Projects/TMD/_Data/tmp/"


[Load_data]
# path to where the input files are located
"folderpath_to_data" = "/media/drive_siegert/RyCu/Projects/TMD/_Data/_TMD_barcodes/Brain/"
"filename_prefix" = "Morphomics.PID1.TMD-radial_distances"

# how the input files are separated
"separated_by" = "Model"
"conditions_to_include" = ["Ctrl_Kxa4h","Ctrl_Kxa48h",]

# dictionary key where to store the loaded data
"morphoframe_name" = "morphoframe"


[Clean_frame]
# if not 0, must contain the filepath to the morphoframe which will then be saved into morphoframe_name
# otherwise, `morphoframe_name` is the morphoframe that will be cleaned up
"morphoframe_filepath" = 0
"morphoframe_name" = "morphoframe"

# remove morphologies if the number of bars is less than the cutoff
"barcode_size_cutoff" = 5

# retain bars whose length satisfy a certain cutoff
# must be an array with three elements, ["greater_than" "less_than" or "within", bar length condition (must be an array if using "within"), "drop" or "keep"]
# the example below keeps bars whose length is greater than 0, and less than 200.
# if not used, comment the elements of `barlength_cutoff` out
"barlength_cutoff" = [ 
            ["less_than", 0, "drop"],
            ["greater_than", 200, "drop"], 
            ["within", [0,200], "keep"],
        ]

# enumerate which conditions will be merged
# must be an array with three elements [a header of the info_frame (is an element of `Input.conditions`),
#                                       a list of conditions that will be merged (must be an array), 
#                                       the new name of the merged conditions]
# if not used, comment the elements of `combine_conditions` out
"combine_conditions" = [
    ["Model", ["Ctrl_Kxa4h", "Ctrl_Kxa48h"], "Ctrl_Kxa"]
]

# enumerate restrictions
# must be an array with three elements [a header of the info_frame (is an element of `Input.conditions`),  
#                                       list of conditions to either drop or keep (must be an array), 
#                                       "drop" or "keep" conditions specified]
# if not used, comment the elements of `restrict_conditions` out
"restrict_conditions" = [
#    ["Region", ["CB", "CN", "OB", "S1", "SN"], "drop"],
#    ["Model", ["Ctrl_Kxa",], "keep"],
]

# I would advise saving the cleaned data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = true

# location where to save the data
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Data/_TMD_barcodes/Brain/"

# if 0, morphOMICs will automatically create a file prefix, i.e., Morphomics.PID[xxx].[barcode_filter].Cleaned.
# Otherwise, this will be used as the file prefix
"file_prefix" = 0



[Bootstrap]
# if not 0, must contain the filepath to the morphoframe
"morphoframe_filepath" = 0
"morphoframe_name" = "morphoframe"

# must be an array with two elements [feature (one of the headers in morphoframe), "bars", "scalar" or "array"]
"feature_to_bootstrap" = ["Barcodes", "bars"]           # bootstraps by collapsing the lists into a single list 
# "feature_to_bootstrap" = ["Barcode_length", "scalar"] # bootstraps by taking the average of an array
# "feature_to_bootstrap" = ["Sholl", "array"]           # # bootstraps by taking the element-wise average of a high-dimensional NumPy array

# use this if you want to constraint your bootstrapping to a subset of conditions that you did not drop using `Clean_frame`
# column name in morphoframe where the bootstrap_conditions are located
"condition_column" = "Model"
# conditions to bootstrap
# if this array is empty, it will bootstrap across all conditions in the morphoframe
"bootstrap_conditions" = [

        ]
        

# which conditions combinations which bootstrapping will consider as a unique condition
"bootstrap_resolution" = [
                    "Region",
                    "Model",
        ]
        
        
# set the seed of the random number, for reproducibility
"rand_seed" = 34151


# if this is opted, N_pop will be calculated as ratio*(total number of morphologies in a given condition combination)
# if 0, you must input N_pop
"ratio" = 0
# number of morphologies to take averages of
# set this to 1 if you don't want to perform bootstrapping
"N_pop" = 15
# number of bootstrap samples to create
"N_samples" = 1000


# where the bootstrapped morphoframes will be stored
"bootstrapframe_name" = "bootstrap_frame"
"morphoinfo_name" = "bootstrap_info"


# I would advise saving the data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = true
# path to folder where to store bootstrapped conditions
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/"
# if 0, morphOMICs will automatically create a file prefix, i.e., Morphomics.PID[xxx].[barcode_filter].Bootstrap.
# Otherwise, this will be used as the file prefix
"file_prefix" = 0


[Persistence_Images]
# if not 0, must contain the filepath to the bootstrapframe
"morphoframe_filepath" = 0
"morphoframe_name" = "bootstrap_frame"


# paramteres for calculating persistence images
# spread of the Gaussian
"bw_method" = 0.5
# how to normalize the persistence image, can be "sum" or "max"
"norm_method" = "sum"
# constraints to the axes limits
"xlims" = [0, 200]
"ylims" = [0, 200]
# if not 0, must point to the location containing the weights to each bar
"barcode_weight" = 0


# I would advise saving the data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = true
# path to folder where to store bootstrapped conditions
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/"
# if 0, morphOMICs will automatically create a file prefix, i.e., Morphomics.PID[xxx].[barcode_filter].Bootstrap.
# Otherwise, this will be used as the file prefix
"file_prefix" = 0


[Mapping]
# !!! IMPORTANT !!!
"F_umap_filepath" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/Morphomics.PID1.Cleaned.UMAP-UMAPfunction3D.pkl"

# if not 0, you MUST specify the location to the persistence images
"PersistenceImages_filepath" = 0

# if 1, you MUST specify the location of the filtered pixel indices before doing the UMAP of the generated phenotypic spectrum
"filter_pixels" = 1
"FilteredPixelIndex_filepath" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/Morphomics.PID1.Cleaned.UMAP-FilteredIndex.pkl"

# if 1, you MUST specify the location of the PCA function used before doing the UMAP of the generated phenotypic spectrum
"run_PCA" = 0
"F_PCA_filepath" = 0

# I would advise saving the data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = true
# path to folder where to store UMAP function and reduced manifold coordinates
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/"
# if 0, morphOMICs will automatically create a file prefix
# Otherwise, this will be used as the file prefix
"file_prefix" = 0


[Prepare_ReductionInfo]
"declare_filepaths" = false
"UMAP_filepath" = 0
"BootstrapInfo_filepath" = 0

# dictionary keys to the metadata
"coordinate_key" = "X_umap"
"morphoinfo_key" = "bootstrap_info"
"coordinate_axisnames" = "UMAP"

# path to folder where to store UMAP function and reduced manifold coordinates
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/"
# if 0, morphOMICs will automatically create a file prefix
# Otherwise, this will be used as the file prefix
"file_prefix" = 0


[Plotting]
# if 0, you must supply Coordinate_filepath AND MorphoInfo_filepath
# else, you can either supply the ReductionInfo_filepath, 
# or if you want to infer the manifold coordinates and morphoinfo_frame from Protocol instance, supply any character other than '0'
"ReductionInfo_filepath" = [
"/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/Morphomics.PID1.Cleaned.ReductionInfo.csv",
"infer",
]
"coordinate_axisnames" = "UMAP"


"coordinate_key" = "X_umap"
"morphoinfo_key" = "bootstrap_info"


# If these are not 0, must point to the location of the manifold coordinates
"Coordinate_filepath" = [ 
# coordinate_filepath1,
# coordinate_filepath2,
]
# If these are not 0, must point to the location of the morpho_infoframe that corresponds to each element of `Coordinate_filepath`
"MorphoInfo_filepath" = [ 
# morphoinfo_filepath1,
# morphoinfo_filepath2,
]

# Location to the color mapping that will be used
# 
"colormap_filepath" = [
    "/media/drive_siegert/RyCu/Projects/TMD/_Tutorials/_morphOMICs_v2_Tutorials/colormap.1.csv",
    "/media/drive_siegert/RyCu/Projects/TMD/_Tutorials/_morphOMICs_v2_Tutorials/colormap.2.csv",
# colapmap_filepath3,
]

# Must correspond to each element in `Coordinate_filepath`
label_prefixes = [
    "SexSpecific",
    "NonSexSpecific",
]

# If you need to substitute the name of a condition in morpho_infoframe, use this
# 
"Substitutions" = [
#    [
#        ["Time", "Adult", "P30"], # replaces all instances of `Adult` in the `Time` column to `P30`
#        ["Model", "Ctrl_Kxa",  "P60"], 
#    ],
#   [ substitutions for morphoinfo_filepath2 ],
]

# Trigger to show the interactive plot
"show_plot" = true

# I would advise saving the data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = true

# path to folder where to store UMAP function and reduced manifold coordinates
"save_folder" = "/media/drive_siegert/RyCu/Projects/TMD/_Results/Brain/"

# if 0, morphOMICs will automatically create a file prefix
# Otherwise, this will be used as the file prefix
"file_prefix" = "Brain_sample"